### ISSUE TITLE
Unused import of AtomicLong

### ISSUE THREAD

**Issue by adaofeliz** [dantheman213/java-spring-mvc-rest-bootstrapped-app#2]
https://github.com/dantheman213/java-spring-gradle-docker-mvc-rest-starter-app/blob/952bb93fd7af703959cd60815b6494948fdf4862/src/main/java/myapp/controllers/HomeController.java#L3

**Comment by dantheman213** [comment]
good catch. I'll update in code or you can also submit a PR.

**Comment by dantheman213** [comment]
Resolved. #c194bbd
